# Permutations

In [1]:
import numpy as np
import permutil as pu

### Complete permutations

**Generation** The most basic function consists in generating a permutation $\sigma$ from $S_n$, the set of all permutations. The permutations are coded as vectors of the first $n$ natural numbers (beginning with 0 here in Python) where each item appears once and once only.
Complete permutations can be defined here as ndarrays with dtype int or list of integers as well.
They can be defined by hand as follows:

In [2]:
perm1 = np.array([3,1,2,0,4])
perm1

array([3, 1, 2, 0, 4])

They can also be randomly generated as follows ($n$ being the length of the permutation):

In [3]:
n=5
perm2 = np.random.permutation(n)
perm2

array([3, 4, 0, 2, 1])

**Operations** *(The following functions are defined in the package [permutil.py](https://github.com/ekhiru/top-k-mallows/blob/master/permutil.py))*.

Two permutations can be composed and the result is a permutation. This operation is not commutative in general. 

In [4]:
pu.compose(perm1, perm2)

array([0, 4, 3, 2, 1])

The inverse of a permutation can also be obtained with:

In [5]:
pu.inverse(perm1)

array([3, 1, 2, 0, 4])

### Top-$k$ rankings

A top-$k$ ranking ($k \le n$) $\sigma$ is a ranking $\sigma = (\sigma(1), \sigma(2), \dotsc, \sigma(n))$ for which only the first $k$ ranks  are known. Hence ranks of items $i$ such that $\sigma(i) \le k$. An example of top-5 rankings (with $n=10$) with the package would be:


In [6]:
partial = np.array([ 4., 0., np.NaN, 1., np.NaN, 3., np.NaN, 2., np.NaN, np.NaN])
partial

array([ 4.,  0., nan,  1., nan,  3., nan,  2., nan, nan])

In [7]:
full = np.array([ 2, 9, 5, 3, 4, 8, 7, 1, 6, 0])

A partial permutation can be composed with a complete permutation using the following function:

In [8]:
pu.compose_partial(partial, full)

[nan, nan, 3.0, 1.0, nan, nan, 2.0, 0.0, nan, 4.0]

The inverse of a top-$k$ rankings is obtained with:

In [9]:
pu.inverse_partial(partial)

array([ 1.,  3.,  7.,  5.,  0., nan, nan, nan, nan, nan])